### ISSUE TITLE
Unable to import any model

### ISSUE THREAD

**Issue by oliveiralberto** [flybywiresim/glTF-Blender-IO-MSFS#3]
**Describe the bug**
I can not import the model

**To Reproduce**
1. Go to '...'file>import>gITF 2.0 for MSFS (.glb/.gltf)
2. Click on 'selectin the model, It doesn't matter which one, the same thing happens with everyone'
3. See error See the screenshot 
4. permissionError:
[WinError 5] Acceso denegado 
location:<unknown location>:-1

**Expected behavior**
Open a model
I did the instalation following this tutorial.
[](https://www.youtube.com/watch?v=R1WkS9UXeNs&list=WL&index=5&t=400s)
**Screenshots**
![Captura de pantalla (1424)](https://user-images.githubusercontent.com/70357882/129377519-bc666785-90b4-4a29-b496-e03d4421d5d1.png)
![Captura de pantalla (1425)](https://user-images.githubusercontent.com/70357882/129377522-4227ab9a-2a92-41fb-8344-28def63a158f.png)
![Captura de pantalla (1426)](https://user-images.githubusercontent.com/70357882/129377524-b20089ac-0053-4df0-a4f5-c078853aaf3a.png)
![Captura de pantalla (1427)](https://user-images.githubusercontent.com/70357882/129380050-c1f00d58-6843-4339-bb91-829dd6f28bc7.png)

https://drive.google.com/drive/folders/1KjQYNeHFq9mcsurscMhIQW8XqDP59PSL?usp=sharing (Same screenshots)

**Version**
 - OS: windows 10 21H1 19043.1165
 - Blender Version 2.92

**Additional context**
I have no idea if this is the right place to ask this. If it is not, I apologize. I would appreciate any help

**Comment by pepperoni505** [comment]
Can you try launching blender as an administrator?

**Comment by oliveiralberto** [comment]
Yes I already did that, and I have got the same result.

**Comment by pepperoni505** [comment]
What's the path for the model you're trying to import?

**Comment by pepperoni505** [comment]
I think I know what the issue is. After looking at your screenshots again, you didn't set the `texconv.exe` path correctly. You just specified the directory, but you need to choose the actual executable.

**Comment by oliveiralberto** [comment]
Hi well. sorry for the delay- I was trying to open FBW a320neo model and Asobo 747 the paths are the following
D:\Users\olive\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\flybywire-aircraft-a320-neo\SimObjects\AirPlanes\FlyByWire_A320_NEO\model
and
D:\Users\olive\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore\asobo-aircraft-b7478i\SimObjects\Airplanes\Asobo_B747_8i\model

In other hand I added the path with te texconv.exe and Well after wait few minute. I have got a new error hahahaha
![Captura de pantalla (1459)](https://user-images.githubusercontent.com/70357882/129457397-ceaee642-3185-47be-aa30-d13e045d7803.png)
![Captura de pantalla (1457)](https://user-images.githubusercontent.com/70357882/129457402-1a2faddd-59d4-47ed-8f5c-2ee9cf3a9df7.png)
![Captura de pantalla (1458)](https://user-images.githubusercontent.com/70357882/129457404-6ebfdc78-a764-48b1-bc85-ad18df663382.png)
In the case of FBW 320 model only can load the rudder section 
![Captura de pantalla (1460)](https://user-images.githubusercontent.com/70357882/129457457-9908d6d0-5dd4-4a39-8031-af744b52c44f.png)

Also try to run it as administrator 

Beforehand thank you very much

**Comment by pepperoni505** [comment]
What's the error for importing the A32NX?

**Comment by oliveiralberto** [comment]
how you can see in the screenshots.  Well, I don't see it saying a particular error.  just give me that report.  and does not load the model.

**Comment by pepperoni505** [comment]
Can you double check to make sure your flight sim path is correct? Watch this video to help: https://cdn.discordapp.com/attachments/754092423562395730/819971302222987284/2021-03-12_11-30-35.mp4

**Comment by oliveiralberto** [comment]
Hi, I just follow your tutorial video. I did exactly that you did and well. I get another error. but in this case finish with something weird line with the name of the another aircraft (diferent as the model that I was opening). I realice can be a incompatible problem. To try I just empty my comunity folder and just left FBW Airbus and start to work fine. 
The model open fine. but i have anothe errors, but i think this is normal. 

Many thank for your help. now is time to learn more. 

For the record the path line on the aircraft problem was flysimware-aircraft-grumman-g44a and carenado-aircraft-ct182t-skylane-g1000

![Captura de pantalla (1462)](https://user-images.githubusercontent.com/70357882/129482783-9924f225-75cd-458f-ab5f-30d03ab65b68.png)
![Captura de pantalla (1463)](https://user-images.githubusercontent.com/70357882/129482790-778a0990-dd27-48df-a4d4-e5f008a18b3c.png)

**Comment by pepperoni505** [comment]
Glad to hear that everything is fixed now! That error you're getting was fixed by d4a067ca4215d9b0601309b857c906f82c4e69d9

**Comment by oliveiralberto** [comment]
Mant thank. I will get a look to fix it
